apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-viki
spec:
  storageClassName: nfs-subdir
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 158.42.104.167
    path: "/mnt/viki"
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-viki
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "nfs-subdir"
  resources:
    requests:
      storage: 1Gi